# Generated by Django 4.2.9 on 2024-08-11 09:31

import accountapp.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-zA-Z_]{5,20}$",
                                "5-20글자 사이의 숫자,영문,언더바만 가능합니다!",
                            )
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_animal", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", accountapp.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AnimalUser",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("animal_num", models.IntegerField(default=0)),
                (
                    "center",
                    models.CharField(blank=True, default="익명의 챠우", max_length=13),
                ),
                ("species", models.CharField(blank=True, max_length=100)),
                ("breed", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=100)),
                (
                    "nickname",
                    models.CharField(blank=True, default="익명의 챠우", max_length=13),
                ),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True,
                        default="default.png",
                        null=True,
                        upload_to="profile_pics/",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AnimalProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_pic",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
                ("bio", models.TextField(blank=True, max_length=100)),
                (
                    "nickname",
                    models.CharField(blank=True, default="익명의 챠우", max_length=13),
                ),
                (
                    "center",
                    models.CharField(blank=True, default="익명의 챠우", max_length=13),
                ),
                (
                    "species",
                    models.CharField(
                        choices=[("0", "고양이"), ("1", "강아지"), ("2", "ETC")],
                        default="0",
                        max_length=2,
                    ),
                ),
                ("kind", models.CharField(blank=True, max_length=10)),
                ("sex", models.CharField(blank=True, max_length=1)),
                ("age", models.CharField(blank=True, max_length=5)),
                ("weight", models.FloatField(blank=True, null=True)),
                ("enter", models.DateTimeField(default=django.utils.timezone.now)),
                ("youtube", models.CharField(blank=True, max_length=100)),
                (
                    "profile_pic_url",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
