# Generated by Django 4.2.9 on 2024-08-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animaluser',
            name='char_num',
            field=models.IntegerField(default=-1),
        ),
    ]
