# Generated by Django 4.2.9 on 2024-08-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_animaluser_char_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animaluser',
            name='char_num',
        ),
        migrations.AddField(
            model_name='user',
            name='char_num',
            field=models.IntegerField(default=-1),
        ),
    ]
