# Generated by Django 4.2.9 on 2024-07-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountapp", "0003_alter_user_school"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="school",
        ),
        migrations.AlterField(
            model_name="profile",
            name="nickname",
            field=models.CharField(blank=True, default="익명의 챠우", max_length=13),
        ),
    ]
