# Generated by Django 4.2.9 on 2024-08-10 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accountapp", "0004_remove_user_school_alter_profile_nickname"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimalUser",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("animal_num", models.IntegerField(default=0)),
                (
                    "center",
                    models.CharField(blank=True, default="익명의 챠우", max_length=13),
                ),
                ("species", models.CharField(blank=True, max_length=100)),
                ("breed", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="is_animal",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="AnimalProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=100)),
                (
                    "nickname",
                    models.CharField(blank=True, default="익명의 챠우", max_length=13),
                ),
                (
                    "center",
                    models.CharField(blank=True, default="익명의 챠우", max_length=13),
                ),
                (
                    "species",
                    models.CharField(
                        choices=[("0", "고양이"), ("1", "강아지"), ("2", "ETC")],
                        default="0",
                        max_length=2,
                    ),
                ),
                ("kind", models.CharField(blank=True, max_length=10)),
                ("sex", models.CharField(blank=True, max_length=1)),
                ("age", models.CharField(blank=True, max_length=5)),
                ("weight", models.FloatField(blank=True, null=True)),
                ("enter", models.DateTimeField(default=django.utils.timezone.now)),
                ("youtube", models.CharField(blank=True, max_length=100)),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True, null=True, upload_to="animal_profile_pics/"
                    ),
                ),
                (
                    "profile_pic_url",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
