# Generated by Django 4.2.9 on 2024-08-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountapp", "0005_animaluser_user_is_animal_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="animalprofile",
            name="profile_pic_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
