version: "3.7"
services:
  redis:
    image: "redis:6.2.6-alpine"
    networks:
      - network
    ports:
      - "6379:6379" 
  django_container:
    image: mongle_django_image:2
    networks:
      - network
    volumes:
      - static-volume:/app/mongle/backend/staticfiles
      - media-volume:/app/mongle/backend/media
    secrets:
      - MYSQL_PASSWORD
      - DJANGO_SECRET_KEY
      - EMAIL_HOST_PASSWORD
    environment:
      REDIS_URL: redis://redis
  react_container:
    image: mongle_react_image:2
    networks:
      - network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - static-volume:/data/static
      - media-volume:/data/media
    ports:
      - "80:80"
      - "443:443"    
  mariadb:
    image: mariadb:10.5
    networks:
      - network
    volumes:
      - maria-database:/var/lib/mysql
    secrets:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
    environment:  
      MYSQL_DATABASE: mongle
      MYSQL_USER: mongle
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD

networks:
  network:

volumes:
  static-volume:
  media-volume:
  maria-database:
  build-volume:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MYSQL_ROOT_PASSWORD:
    external: true
  MYSQL_PASSWORD:
    external: true
  EMAIL_HOST_PASSWORD:
    external: true