# Generated by Django 4.2.9 on 2024-08-16 01:04

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_post_likes_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="post_files/",
                validators=[
                    mainapp.models.validate_file_extension,
                    mainapp.models.validate_file_size,
                ],
            ),
        ),
    ]
